### ISSUE TITLE
Low severity vulnerability found on hawk@2.3.1

### ISSUE THREAD

**Issue by sagivo** [twilio/twilio-node#181]
**Version:**
2.9.1
### Code Snippet

running 
`snyk test` will result:

```
✗ Low severity vulnerability found on hawk@2.3.1
- desc: Regular Expression Denial of Service
- info: https://snyk.io/vuln/npm:hawk:20160119
- from: twilio@2.9.1 > request@2.55.0 > hawk@2.3.1
No direct dependency upgrade can address this issue.
Run `snyk wizard` to explore remediation options.
```
### Feature Request

please update ASAP to newer hawk `request` version

**Comment by feross** [comment]
This is affecting my app as well. Please update `request` to a newer version.

More information: https://nodesecurity.io/advisories/77

twilio@2.9.1 > request@2.55.0 > hawk@2.3.1

**Comment by sagivo** [comment]
meanwhile in case you use `synk` you can add this to your `.syck` file:
```
patch:
  'npm:request:20160119':
    - twilio > request:
        patched: '2016-08-05T20:31:33.021Z'
  'npm:hawk:20160119':
    - twilio > request > hawk:
        patched: '2016-08-05T20:31:33.021Z'
```
